### ISSUE TITLE
Jitpack problem

### ISSUE THREAD

**Issue by wlmirand** [FidelLimited/fidel-android#11]
Hello. This week, I noticed my CI environment stopped building and after checking the Logs, I got the message:

Could not resolve all files for configuration ':app:envTestCompileClasspath'.
   > Could not resolve com.github.FidelLimited:android-sdk:1.3.2.
     Required by:
         project :app
      > Could not resolve com.github.FidelLimited:android-sdk:1.3.2.
         > Could not get resource 'https://jitpack.io/com/github/FidelLimited/android-sdk/1.3.2/android-sdk-1.3.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/FidelLimited/android-sdk/1.3.2/android-sdk-1.3.2.pom'. Received status code 401 from server: Unauthorized

I tried open the POM file using the URL, and my browser display an Authentication Dialog.
Then, I cleared my Local Gradle Cache and I could see the same message on my Local Machine.
Also, tried to update the version to 1.5.3 at Gradle, but got the same issue.

Thanks

**Comment by ccorneliu** [comment]
Hello @wlmirand,

The issue should be resolved now. We needed to re-authorize Jitpack to make/provide builds. Sorry for the inconvenience of the build not being available. Please let us know if you need more help with the SDK.

**Comment by wlmirand** [comment]
Hello @ccorneliu. It worked

Thanks a lot.
