### ISSUE TITLE
Jitpack problem

### ISSUE THREAD

**Issue by wlmirand** [FidelLimited/fidel-android#13]
Hello everyone.
Again, I got the same issue reported at: [https://github.com/FidelLimited/fidel-android/issues/11](https://github.com/FidelLimited/fidel-android/issues/11):

> Could not resolve com.github.FidelLimited:android-sdk:1.5.3.
     Required by:
         project :app
      > Could not resolve com.github.FidelLimited:android-sdk:1.5.3.
         > Could not get resource 'https://jitpack.io/com/github/FidelLimited/android-sdk/1.5.3/android-sdk-1.5.3.pom'.
            > Could not GET 'https://jitpack.io/com/github/FidelLimited/android-sdk/1.5.3/android-sdk-1.5.3.pom'. Received status code 403 from server: Forbidden

May you please help me?
Thanks and best regards

**Comment by mrfreitas** [comment]
Hi Fidel team, any update on this issue?

**Comment by ccorneliu** [comment]
Hello @wlmirand, @mrfreitas,

Please try again. It should work now.

Thank you for your patience!

**Comment by wlmirand** [comment]
Hello @ccorneliu. Sorry for the late reply.
The build is working.

Thanks and best regards
