### ISSUE TITLE
Jitpack problem (again!)

### ISSUE THREAD

**Issue by Dirklectisch** [FidelLimited/fidel-android#14]
Hello, 

Unfortunately the same issue that was reported earlier is reoccurring. The dependency on Jitpack is unavailable. This is breaking all our Android builds at the moment. 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processReleaseResources'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.github.FidelLimited:android-sdk:1.7.2.
     Searched in the following locations:
       - file:/Users/dirklectisch/Projects/IAGLoyaltyMobile/node_modules/react-native/android/com/github/FidelLimited/android-sdk/1.7.2/android-sdk-1.7.2.pom
       - file:/Users/dirklectisch/Projects/IAGLoyaltyMobile/node_modules/jsc-android/dist/com/github/FidelLimited/android-sdk/1.7.2/android-sdk-1.7.2.pom
       - https://repo.maven.apache.org/maven2/com/github/FidelLimited/android-sdk/1.7.2/android-sdk-1.7.2.pom
       - https://dl.google.com/dl/android/maven2/com/github/FidelLimited/android-sdk/1.7.2/android-sdk-1.7.2.pom
       - https://www.jitpack.io/com/github/FidelLimited/android-sdk/1.7.2/android-sdk-1.7.2.pom
       - file:/Users/dirklectisch/Projects/IAGLoyaltyMobile/node_modules/react-native-background-fetch/android/libs/com/github/FidelLimited/android-sdk/1.7.2/android-sdk-1.7.2.pom
       - file:/Users/dirklectisch/Projects/IAGLoyaltyMobile/node_modules/@notifee/react-native/android/libs/com/github/FidelLimited/android-sdk/1.7.2/android-sdk-1.7.2.pom
     Required by:
         project :app > project :fidel-react-native
```

Same problem as these issues it seems.

https://github.com/FidelLimited/fidel-android/issues/13
https://github.com/FidelLimited/fidel-android/issues/11

Thanks for you help.

**Comment by iamgraeme** [comment]
@Dirklectisch Did they sort this out? I seem to be having the same issue

**Comment by Dirklectisch** [comment]
@iamgraeme It's a recurring problem, it was fixed back then but might be back now? I would get in touch through an official support channel with them.

**Comment by leovido** [comment]
This is still a known issue and recurring on the same project.

**Comment by valllllll2000** [comment]
@kuriishu27 as commented here https://github.com/FidelLimited/fidel-android/issues/15#issuecomment-1446048268, it seems to be fixed for now, please comment in that new issue if it does not work for you. Will close this issue to have every message in the same thread.
