### ISSUE TITLE
What is Present the activity?

### ISSUE THREAD

**Issue by amigax** [FidelLimited/fidel-android#4]
In the docs I see: Present the activity. I dont know what activity this is though?
Fidel.present(YourActivityClass.this); where does YourActivityClass come from?

**Comment by ccorneliu** [comment]
Hi @amigax ! 

Sorry for the unclear documentation. We'll work on improving it. The `present` function just takes an `Activity` as a parameter: 

`public static void present(Activity startingActivity)`

We use that `startingActivity` to call `startActivityForResult` and present our UI which allows the user to enter the card information. This is the activity that will also receive the result of the card linking process via the `onActivityResult` function. Please let me know, if this is clear, or if there is anything that I can clarify related to showing our card information activity.

Thanks!
Cornel

**Comment by amigax** [comment]
thank you!..
