### ISSUE TITLE
termsConditionsURL  doesnt exist

### ISSUE THREAD

**Issue by amigax** [FidelLimited/fidel-android#6]
in Android it seems that Fidel.termsConditionsURL doesnt exist.

**Comment by ccorneliu** [comment]
@amigax , please make sure that you're using the latest version of the Android SDK. This property is definitely there. If you upgraded recently, please make sure that you're not using a cached version of the old SDK. 

If you still do not see this property, please provide some more details:
* The SDK version that you're using.
* The integration method that you chose (via Jetpack or just by importing the .aar)

**Comment by amigax** [comment]
how do you use the latest sdk? i seem to be using old one. installed via jetpack implementation 'com.github.FidelLimited:android-sdk:1.3.1'

**Comment by amigax** [comment]
OK  upgraded to 1.5.1 in gradle, now termsConditionsURL works, but country does not.

**Comment by ccorneliu** [comment]
@amigax Please check the CHANGELOG to understand the updates. You will notice that we replaced the `country` property with the [`allowedCountries`](https://github.com/FidelLimited/fidel-android#allowedcountries) property to allow developers to support all Fidel supported countries, a subset of the supported countries or just one (like it was possible with the old `country` property). Please check the documentation in the README file of this repository for details.
